### ISSUE TITLE
Consistência no reports

### ISSUE THREAD

**Issue by danilexx** [devarthurribeiro/covid19-brazil-api#12]
a abreviação dos estados as vezes fica localizado na propriedade uf do objeto do estado e o nome por extenso na propriedade state, mas as vezes esse valor é trocado

**Comment by danilexx** [comment]
dia 21
![Screenshot_20200322-204410_Chrome](https://user-images.githubusercontent.com/42390775/77266349-fd9f2a80-6c7d-11ea-8fb5-f6546469210b.jpg)

dia 22 
![Screenshot_20200322-204345_Chrome](https://user-images.githubusercontent.com/42390775/77266387-0e4fa080-6c7e-11ea-9c06-eeb0955d7aa3.jpg)

**Comment by danilexx** [comment]
uf trocou de lugar com state e assim entregando informações sem consistência

**Comment by devarthurribeiro** [comment]
Corrigido no último update 

Closes: #12

**Comment by devarthurribeiro** [comment]
Corrigido no último update!
