### ISSUE TITLE
Campos "uf" e "state" invertidos

### ISSUE THREAD

**Issue by gdeggau** [devarthurribeiro/covid19-brazil-api#14]
Após o dia 19/03 é possível observar que os valores dos campos UF e STATE mudaram. 

E.g.: antes do dia 19/03 o campo UF recebia o nome do estado (Santa Catarina) e o campo STATE recebia a sigla (SC). Após o dia 19/03 foi invertido, o campo UF começou a receber a sigla (SC) e o campo STATE começou a receber o nome do estado (Santa Catarina).

Porém o histórico dos dados antes do dia 19/03 não foram invertidos, causando assim problemas por exemplo para criar um dashboard com índices de evolução por estado.

Seria possível inverter os valores inferior ao dia 19/03 para esses campos na base de dados?

![states](https://user-images.githubusercontent.com/37387111/77329770-37634600-6cfd-11ea-837d-96af8a4688b6.png)

**Comment by devarthurribeiro** [comment]
Realmente teve esse problema, vou corrigir toda base de dados assim que possível. Obrigado pela dica!

**Comment by devarthurribeiro** [comment]
Feito @gdeggau

**Comment by gdeggau** [comment]
> Feito @gdeggau

Show de bola, já estão aparecendo corretamente! Parabéns pelo projeto.
