### ISSUE TITLE
Agradecimento!

### ISSUE THREAD

**Issue by vitorhugosg** [devarthurribeiro/covid19-brazil-api#16]
Venho por meio deste agradecer pelo desenvolvimento da API.

Eu tinha feito com outra API, porém os dados ficaram desatualizados desde o dia 18.

Logo agora to usando a API de vocês.

Parabéns pelo trabalho coloquei os devidos créditos.

Gostaria de saber se tem uma rota que eu consiga todos os históricos para fazer gráficos, desde já agradecido ;)

Segue link do projeto: https://levantelab.com.br/mapa_coronavirus

Parabéns.

**Comment by devarthurribeiro** [comment]
Obrigado pelos elogios!!! Vou colocar essa opção de rota assim que possível!

**Comment by devarthurribeiro** [comment]
Seu site ficou muito bom, vou colocar no showcase!

**Comment by vitorhugosg** [comment]
Vlw irmão tamo junto, ótimo trabalho de vocês obrigado por compartilhar as informações! :)

**Comment by amdrade** [comment]
Muito legal o projeto, parabéns pela iniciativa. Outra fonte de dados por ser essa:
[Brasil.io covid19 ](https://brasil.io/dataset/covid19/caso)

**Comment by vitorhugosg** [comment]
Massa mano, eu agora to tentando fazer o histórico com gráfico, vou implementar esse fim de semana
