### ISSUE TITLE
Coronavirus COVID-19 system

### ISSUE THREAD

**Issue by rendergraf** [devarthurribeiro/covid19-brazil-api#19]
Saudações a todos.

Antes de tudo, parabenizá-lo pelo projeto da API brasileira do Coronavirus, excelente sistema.

Sinto muito pela ousadia dessa maneira, mas gostaria de dizer que, desde os meus quarenta anos, trabalho em um projeto pessoal para explicar aos meus filhos alguns exercícios de javascript e dados. Estamos trabalhando neste projeto e acho que pode ser útil para quem quiser, relatar e representar graficamente dados por país ou mais.

Vou deixar o link para o repositório para que você possa vê-lo e o link do site de trabalho.

Site: https://covidvenezuela.github.io/covid19-venezuela/
Repositório do Github: https://github.com/covidvenezuela/covid19-venezuela

Estamos prontos para responder a qualquer pergunta que você tiver.

Muito obrigado e desculpe minha ousadia.
Xavier

**Comment by devarthurribeiro** [comment]
Obrigado!! 

Vou olhar seu repositório.

**Comment by devarthurribeiro** [comment]
Ficou muito bom, Parabéns!
