### ISSUE TITLE
Adicionar .env.example

### ISSUE THREAD

**Issue by gabrielccarvalho** [devarthurribeiro/covid19-brazil-api#2]
remover o * em .env* no .gitignore e disponibilizar um arquivo .env.example contendo o esqueleto das variáveis globais utilizadas para fins de desenvolvimento. 
Dessa forma o arquivo com as variáveis usadas em produção ficam protegidas e outros desenvolvedores podem ajudar no projeto.

**Comment by devarthurribeiro** [comment]
Vou adicionar de acordo com  a doc do next

https://nextjs.org/docs/api-reference/next.config.js/environment-variables

**Comment by devarthurribeiro** [comment]
Feito!

**Comment by devarthurribeiro** [comment]
Feito.
