### ISSUE TITLE
Dúvida de uso

### ISSUE THREAD

**Issue by gbhgit** [devarthurribeiro/covid19-brazil-api#21]
Primeiramente parabéns pela API desenvolvida, é altamente útil para atualizarmos e estudarmos os dados do Covid19. 

Gostaria de saber se o uso dessa API é livre e se está versão é estavél ela irá continuar em produção ?

**Comment by devarthurribeiro** [comment]
Obrigado pelos elogios! O uso da api e livre e continuaremos o desenvolvimento. O serviço se encontra estável, você pode consultar os logs no site.
