### ISSUE TITLE
Obrigado pelo projeto!

### ISSUE THREAD

**Issue by felipemarinho97** [devarthurribeiro/covid19-brazil-api#22]
Opa, primeiramente gostaria de parabenizar pelo trabalho feito! E dizer que, graças à essa API, foi possível dar vida a um sistema para vizualizar graficamente a evolução dos casos da doença. :tada: 

Fiz ele todo se baseando na sua API, inclusive visualmente :smile:  rsrs

Mas tem um detalhe.. pra poder pegar os dados históricos, precisei implementar consultando cada data individualmente. Acredito que seria melhor se fosse possível consultar tudo com apenas uma requisição.

Link do projeto: [https://github.com/felipemarinho97/covid-19-brazil-map](https://github.com/felipemarinho97/covid-19-brazil-map)

Valeu!

**Comment by devarthurribeiro** [comment]
Obrigado pelos elogios e parabéns pelo site. Vamos adicionar esse endpoint!
