### ISSUE TITLE
Retorno das informações resumidas

### ISSUE THREAD

**Issue by lucassdr** [devarthurribeiro/covid19-brazil-api#23]
Olá, boa noite.

Atualmente para recuperar as informações abaixo é necessário fazer uma chamada em `/api/report/v1/brazil`. Porém, eu acabo fazendo duas chamadas, uma dos estados e essa, só para pegar as informações básicas. Na verdade, no meu caso, eu preciso mais do **updated_at**. Seria possível incluir **updated_at** na chamada `/api/report/v1/`?

```
"data": {
        "country": "Brazil",
        "cases": 3787,
        "confirmed": 3904,
        "deaths": 111,
        "recovered": 6,
        "updated_at": "2020-03-28T23:05:25.000Z"
    }
```

Obrigado desde já pela disponibilização dos dados e excelente trabalho.

**Comment by devarthurribeiro** [comment]
O updated_at é representado por datetime no /api/report/v1/

**Comment by lucassdr** [comment]
Mas dentro de cada nó (estado), correto?

**Comment by devarthurribeiro** [comment]
Exato! Os dados do `/api/report/v1/brazil ` são de outro dataset, esse atualiza várias vezes durante o dia. Já `/api/report/v1/` só atualiza quando o boletim do ministério da saúde é divulgado.

**Comment by lucassdr** [comment]
Entendi. É pq RJ e SP já estão atualizados com dados de hoje, mas lá ainda está dia 25.

**Comment by devarthurribeiro** [comment]
Vou verificar

**Comment by devarthurribeiro** [comment]
Temos um bug!

**Comment by devarthurribeiro** [comment]
Vou identificar a cause e seguida corrigir os dados.

**Comment by lucassdr** [comment]
Ok. Muito obrigado pela presteza a respeito.
Estou deixando aqui meu Instagram, caso necessite contato.
Instagram: @lucassdr
