### ISSUE TITLE
Dados de tempo adicionais em datetime

### ISSUE THREAD

**Issue by KZTN** [devarthurribeiro/covid19-brazil-api#30]
Qual a forma da data provido pelo datetime é formatado?
Ao solitiar uma requisição da última vez que os dados foram atualizados, recebo uma resposta como exemplo: 2020-04-06T22:17:18.006Z

Que tipo de informação se refere à 006z?

**Comment by devarthurribeiro** [comment]
Esse padrão é o iso date e os últimos dígitos correspondem ao timezone.
