### ISSUE TITLE
Dúvida no resultado de mortes

### ISSUE THREAD

**Issue by chrystoffer** [devarthurribeiro/covid19-brazil-api#36]
Primeiramente, parabéns aos envolvidos sobre a API!
Estou com dúvida quanto ao resultado de mortes por dia... utilizei o método https://covid19-brazil-api.now.sh/api/report/v1/brazil/20200420 para pegar os dados do dia 20/04/2020 e ao somar todas as mortes o resultado foi 2845. Porém, no dia 21/04/2020 (https://covid19-brazil-api.now.sh/api/report/v1/brazil/20200421) o resultado é de 2741.
Utilizando o método https://covid19-brazil-api.now.sh/api/report/v1/brazil me retorna que tem 2769 mortes... Porque essa diferença no dia 20?

>  2020-04-01 = 241
 2020-04-02 = 312
 2020-04-03 = 359
 2020-04-04 = 432
 2020-04-05 = 486
 2020-04-06 = 553
 2020-04-07 = 667
 2020-04-08 = 800
 2020-04-09 = 941
 2020-04-10 = 1056
 2020-04-11 = 1124
 2020-04-12 = 1223
 2020-04-13 = 0
 2020-04-14 = 1532
 2020-04-15 = 1736
 2020-04-16 = 1924
 2020-04-17 = 2141
 2020-04-18 = 2352
 2020-04-19 = 2462
 2020-04-20 = 2845
 2020-04-21 = 2741

Obtive esses resultados na somatória de mortes de todos os estados. No dia 13 não retorna nenhuma informação (https://covid19-brazil-api.now.sh/api/report/v1/brazil/20200413) e no dia 20 o resultado fica muito maior (comparado ao bing.com.br/covid)

**Comment by devarthurribeiro** [comment]
Olá @chrystoffer essa diminuição ocorre devido algumas mortes serem descartadas, por erros ou resultados dos exames que estão pendentes, em  relação ao dia 2020-04-13, não foi gerado o relatório desse dia, vou corrigir isso.

**Comment by chrystoffer** [comment]
> Olá @chrystoffer essa diminuição ocorre devido algumas mortes serem descartadas, por erros ou resultados dos exames que estão pendentes, em relação ao dia 2020-04-13, não foi gerado o relatório desse dia, vou corrigir isso.

Obrigado pelas informações  :)
