### ISSUE TITLE
Atualização dos dados parou?

### ISSUE THREAD

**Issue by ribsousa** [devarthurribeiro/covid19-brazil-api#38]
Os dados dos estados do Brasil năo está sendo mais atualizada?

**Comment by devarthurribeiro** [comment]
Oi @ribsousa, teve um problema no crawler, mas já fiz a [correção](https://github.com/devarthurribeiro/covid19-brazil-api/commit/b66e1b7eddde33552b76d3f3a18dd512b668172a). Infelizmente estou com pouco tempo para manter a API.
