### ISSUE TITLE
Métodos que listam estados estão com as propriedades UF e state trocadas na documentação

### ISSUE THREAD

**Issue by raphacmartin** [devarthurribeiro/covid19-brazil-api#39]
Na documentação dos métodos, nos exemplos de retorno, todos métodos que retornam dados por estado estão mostrando que retornam a sigla do estado na propriedade state e o nome do estado na propriedade UF.
Porém, ao consumir os métodos vemos que o que nos retorna é o contrário (UF contendo a sigla e state contendo o nome).

Documentação:
![Captura de Tela 2020-05-25 às 22 26 16](https://user-images.githubusercontent.com/18668732/82851750-2ee2e380-9ed7-11ea-813f-26c8a073cece.png)

Consumindo o serviço usando Postman:
![Captura de Tela 2020-05-25 às 22 26 57](https://user-images.githubusercontent.com/18668732/82851744-2be7f300-9ed7-11ea-8079-44e1511193bc.png)

**Comment by devarthurribeiro** [comment]
Resolvido.
