### ISSUE TITLE
Continua rodando na porta 3000

### ISSUE THREAD

**Issue by gabrielmoura33** [devarthurribeiro/covid19-brazil-api#40]
Não sei poq mas o app continua rodando na porta 3000 mesmo sem estar rodando, 
alguem sabe poq?

**Comment by devarthurribeiro** [comment]
Oi @gabrielmoura33 

Pare o processo de forma manual, assim como mostra esse post. 
https://stackoverflow.com/questions/39322089/node-js-port-3000-already-in-use-but-it-actually-isnt
